Fix develop pull request
chocom01/to-do-laravel pull request #7
Opened 2021-12-10 14:09 UTC by chocom01

2021-12-29 14:48 UTC, nazar-linkup requested changes

2021-12-29 14:48 UTC, nazar-linkup commented on app/Http/Requests/QueryStringRequest.php
> +class QueryStringRequest extends FormRequest
Дивна назва класу, глянь як в документації названі ті класи

2021-12-29 14:48 UTC, nazar-linkup commented on app/Models/Task.php
> +    public function scopeFilter(object $query, array $validated)
- $query це не просто обєкт це обєкт конкретного класу, а то ти написав цей метод так, ніби я туди може передати обєкт будь якого класу. 
- $validated взагалі ні про що не говорить.Це в контроллері ти хнаєш що метод валідейтед віддає масив провалідованих валідатором даних. А тут ця назва взагалі нічого нам не каже

2021-12-29 14:48 UTC, nazar-linkup commented on database/factories/TaskFactory.php
> -            'priority_id' => Priority::factory()
Та твоя фабрица мала б повністю таск створювати, з юзером, статусом і пріоритетом. Просто, що повертає Status::factory() - обєкт статуса чи ід статуса?

2021-12-29 14:48 UTC, nazar-linkup commented on database/seeders/StatusSeeder.php
> +                'slug' => 'in_progress'
https://laravel.com/docs/8.x/helpers#method-str-slug
можеш оце використовувати, що б вручну не писати

2021-12-29 14:48 UTC, nazar-linkup commented on database/seeders/TaskSeeder.php
> +            'user_id' => 2,
Знову ж таки, просто циферки ні про що не говорять. `User::query()->inRandomOrder()->first()->getKey()`

2021-12-29 14:48 UTC, nazar-linkup commented on resources/views/tasks/edit.blade.php
> +    <link href="{{ asset('/css/form.css') }}" rel="stylesheet">
ти одні і ті самі стилі підключаєш в кожному файлі. Підключи їх один раз в батьківському шаблоні і все

2021-12-29 14:48 UTC, nazar-linkup commented on resources/views/components/task/selector.blade.php
> +        <option value="{{ $record->id }}" {{ old("$column", $object->$column ?? null) == $record->id ? 'selected' : '' }}>
це ти через звязки таска до статуса і пріоритетності так виводиш список можливих опцій?

2022-01-04 17:01 UTC, chocom01 commented on app/Http/Requests/QueryStringRequest.php
> +class QueryStringRequest extends FormRequest
поміняв

2022-01-04 17:13 UTC, chocom01 commented on app/Models/Task.php
> +    public function scopeFilter(object $query, array $validated)
поміняв на конкретний обєкт
переназвав validated на filteringParams

2022-01-04 17:17 UTC, chocom01 commented on database/factories/TaskFactory.php
> -            'priority_id' => Priority::factory()
в іншій гілці це був видалив

2022-01-04 17:43 UTC, chocom01 commented on database/seeders/TaskSeeder.php
> +            'user_id' => 2,
переробив на те, що ти написав

2022-01-04 17:48 UTC, chocom01 commented on resources/views/tasks/edit.blade.php
> +    <link href="{{ asset('/css/form.css') }}" rel="stylesheet">
перемістив

2022-01-10 13:27 UTC, chocom01 commented on resources/views/components/task/selector.blade.php
> +        <option value="{{ $record->id }}" {{ old("$column", $object->$column ?? null) == $record->id ? 'selected' : '' }}>
вже поняв, що фігня і потім переробив

2022-01-10 13:27 UTC, merged