Api resources
chocom01/to-do-laravel pull request #8
Opened 2021-12-17 16:13 UTC by chocom01

2021-12-29 15:04 UTC, nazar-linkup requested changes

2021-12-29 15:04 UTC, nazar-linkup commented on app/Services/TaskService.php
> +    }
Я б не привязувався на стілки до реквеста. А в тут зробив тільки метод для вибірки тасків з тою фільтрацією що в тебе є, а реквест залишити можна в контроллері. 
Що тобі ще десь походу програми треба буде використати цей метод (зробити якусь вибірку тасків), де не буде обєкту реквеста? Ти це вже перевикористати не зможеш нормально

2021-12-29 15:04 UTC, nazar-linkup commented on app/Http/Requests/TaskValidationRequest.php
> +            'priority_id' => [$postRule, Rule::exists('priorities', 'id')]
І нема ерорів коли ти пусту стрічку пепредаєш як правило валідації? 
Навіть якщо не ерорить, то виглядає так собі.

2021-12-29 16:22 UTC, chocom01 commented on routes/api.php
> +    ]);
я вже не памятаю для чого це ставив, видалив

2021-12-29 16:39 UTC, chocom01 commented on app/Models/Task.php
> +        $query->orderBy($validated['orderBy'] ?? 'name', $validated['sortBy'] ?? 'asc')->orderBy('id', 'asc');
бо коли я міняю з 10 елементів на сторінці на 50, список по-іншому трошки відображається

2021-12-29 16:49 UTC, chocom01 commented on app/Http/Controllers/Api/TaskController.php
> +        return response('Task was deleted', 204);
переніс аналогічно destroy & update

2021-12-29 16:50 UTC, chocom01 commented on app/Services/TaskService.php
> +        $task->save();
поняв, забув що create() так само вертає створений таск

2021-12-29 16:56 UTC, chocom01 commented on app/Http/Requests/TaskValidationRequest.php
> +            'priority_id' => [$postRule, Rule::exists('priorities', 'id')]
по суті поняв, що дані автоматично підтягуються і будуть пустими тільки якщо юзер очистить, тому поставив щоб завжди 'required'

2021-12-30 09:21 UTC, chocom01 commented on app/Services/TaskService.php
> +    }
зрозумів, переробив це і так само інші екшини

2022-01-04 15:28 UTC, merged